(()=>{"use strict";
const CATALOG=["AXIS P3278-LVE","AXIS P3268-LVE","AXIS M3088-V","AXIS M3086-V","AXIS M4328-P","AXIS M4318-PLVE","AXIS Q3538-LVE","AXIS P1468-LE","AXIS P3267-LVE","Hikvision DS-2CD2387G2-LU","Dahua IPC-HDW3849H-AS-PV"];
const S={objects:[],selected:null,history:[],plan:null,scale:null,drag:null};
const $=s=>document.querySelector(s),stage=$("#stage"),plan=$("#plan"),empty=$("#empty"),status=$("#status");
const snap=()=>JSON.stringify({objects:S.objects,selected:S.selected,scale:S.scale});
function push(){S.history.push(snap());if(S.history.length>60)S.history.shift()}
function next(type){let p=type==="camera"?"K":type==="switch"?"SW":"NVR",n=1;while(S.objects.some(o=>o.name===p+n))n++;return p+n}
function add(type,x=.5,y=.5){push();let o={id:(crypto.randomUUID?crypto.randomUUID():Date.now()+"-"+Math.random()),type,name:next(type),x,y,rot:0,model:type==="camera"?CATALOG[0]:""};S.objects.push(o);S.selected=o.id;render()}
function esc(s){return String(s).replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]))}
function render(){stage.querySelectorAll(".obj,.objLabel,.dir").forEach(e=>e.remove());for(const o of S.objects){if(o.type==="camera"){let dir=document.createElement("div");dir.className="dir";dir.style.left=o.x*100+"%";dir.style.top=o.y*100+"%";dir.style.transform="rotate("+o.rot+"deg)";stage.append(dir)}let d=document.createElement("div");d.className="obj "+o.type+(o.id===S.selected?" selected":"");d.textContent=o.name;d.style.left=o.x*100+"%";d.style.top=o.y*100+"%";d.dataset.id=o.id;stage.append(d);let l=document.createElement("div");l.className="objLabel";l.textContent=o.name+(o.model?" · "+o.model:"");l.style.left=o.x*100+"%";l.style.top=o.y*100+"%";stage.append(l)}empty.style.display=(S.plan||S.objects.length)?"none":"grid";inspector();list();$("#undoBtn").disabled=!S.history.length}
function inspector(){let o=S.objects.find(x=>x.id===S.selected),el=$("#inspector");if(!o){el.innerHTML="Välj ett objekt på ritningen.";return}if(o.type!=="camera"){el.innerHTML="<b>"+esc(o.name)+"</b><p>Typ: "+esc(o.type)+"</p>";return}
el.innerHTML='<b>'+esc(o.name)+'</b><p>Kamerapositionen är låst till där du placerar den.</p><label>Modell<select id="modelSelect">'+CATALOG.map(m=>'<option '+(m===o.model?'selected':'')+'>'+esc(m)+'</option>').join("")+'</select></label><label>Rotation <b id="rotVal">'+o.rot+'°</b><input id="rotInput" type="range" min="0" max="359" value="'+o.rot+'"></label><div class="rotateBtns"><button data-r="-45">↶ 45°</button><button data-r="45">45° ↷</button></div>';
$("#modelSelect").onchange=e=>{push();o.model=e.target.value;render()};$("#rotInput").oninput=e=>{o.rot=+e.target.value;$("#rotVal").textContent=o.rot+"°";render()};$("#rotInput").onchange=()=>push();el.querySelectorAll("[data-r]").forEach(b=>b.onclick=()=>{push();o.rot=(o.rot+ +b.dataset.r+360)%360;render()})}
function list(){$("#camList").innerHTML=S.objects.filter(o=>o.type==="camera").map(o=>'<div class="row" data-sel="'+o.id+'"><b>'+esc(o.name)+'</b><br><small>'+esc(o.model)+'</small></div>').join("")}
stage.addEventListener("pointerdown",e=>{let d=e.target.closest(".obj");if(!d)return;e.preventDefault();let o=S.objects.find(x=>x.id===d.dataset.id);S.selected=o.id;push();S.drag={id:o.id,pointer:e.pointerId};try{d.setPointerCapture(e.pointerId)}catch{}render()});
stage.addEventListener("pointermove",e=>{if(!S.drag||e.pointerId!==S.drag.pointer)return;e.preventDefault();let r=stage.getBoundingClientRect(),o=S.objects.find(x=>x.id===S.drag.id);if(!o)return;o.x=Math.max(.015,Math.min(.985,(e.clientX-r.left)/r.width));o.y=Math.max(.02,Math.min(.98,(e.clientY-r.top)/r.height));render()});
function endDrag(e){if(!S.drag)return;S.drag=null;render()}stage.addEventListener("pointerup",endDrag);stage.addEventListener("pointercancel",endDrag);
stage.addEventListener("click",e=>{let d=e.target.closest(".obj");if(d){S.selected=d.dataset.id;render()}});
$("#camList").onclick=e=>{let r=e.target.closest("[data-sel]");if(r){S.selected=r.dataset.sel;render()}};
document.querySelectorAll("[data-add]").forEach(b=>b.onclick=()=>add(b.dataset.add,.5,.5));
$("#planBtn").onclick=()=>$("#planFile").click();$("#planFile").onchange=e=>{let f=e.target.files[0];if(!f)return;let rd=new FileReader();rd.onload=()=>{S.plan=rd.result;plan.src=S.plan;empty.style.display="none";status.textContent="Ritning laddad.";try{localStorage.setItem("cctvPlan",S.plan)}catch{status.textContent="Ritning laddad, men för stor för lokal lagring."}};rd.readAsDataURL(f)};
$("#undoBtn").onclick=()=>{if(!S.history.length)return;let q=JSON.parse(S.history.pop());S.objects=q.objects;S.selected=q.selected;S.scale=q.scale;render()};
$("#newBtn").onclick=()=>{if(!confirm("Skapa nytt tomt projekt?"))return;push();S.objects=[];S.selected=null;S.plan=null;plan.removeAttribute("src");localStorage.removeItem("cctvPlan");render()};
$("#saveBtn").onclick=()=>{localStorage.setItem("cctvProject",JSON.stringify({objects:S.objects,scale:S.scale,name:$("#projectName").value}));status.textContent="Projekt sparat lokalt i denna webbläsare."};
$("#scaleBtn").onclick=()=>status.textContent="Tvåpunktskalibrering kommer i nästa byggsteg.";
let saved=localStorage.getItem("cctvProject");if(saved)try{let q=JSON.parse(saved);S.objects=q.objects||[];S.scale=q.scale||null;$("#projectName").value=q.name||"Testprojekt"}catch{}let p=localStorage.getItem("cctvPlan");if(p){S.plan=p;plan.src=p}render();
})();