(()=>{"use strict";
const CAT=window.CCTV_CATALOG||{cameras:[],switches:[],nvrs:[]},S={objects:[],selected:null,history:[],plan:null,scale:null};const $=s=>document.querySelector(s),stage=$("#stage"),plan=$("#plan"),empty=$("#empty"),status=$("#status"),overlay=$("#overlay");const snap=()=>JSON.stringify({objects:S.objects,selected:S.selected,scale:S.scale});function push(){S.history.push(snap());if(S.history.length>60)S.history.shift()}function next(t){let p=t==="camera"?"K":t==="switch"?"SW":"NVR",n=1;while(S.objects.some(o=>o.name===p+n))n++;return p+n}function models(t){return t==="camera"?CAT.cameras:t==="switch"?CAT.switches:CAT.nvrs}function defaultModel(t){return models(t)[0]?.model||""}function add(type,x=.5,y=.5){push();S.objects.push({id:crypto.randomUUID(),type,name:next(type),x,y,rot:0,range:.22,model:""});S.selected=S.objects.at(-1).id;render()}function esc(s){return String(s).replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]))}
function camSpec(o){return CAT.cameras.find(c=>c.model===o.model)||{hfov:90}}function pt(cx,cy,r,a){let q=a*Math.PI/180;return [cx+Math.cos(q)*r,cy+Math.sin(q)*r]}function wedge(cx,cy,r,rot,hfov){if(hfov>=180)return "";let a=pt(cx,cy,r,rot-hfov/2),b=pt(cx,cy,r,rot+hfov/2);return cx+","+cy+" "+a[0]+","+a[1]+" "+b[0]+","+b[1]}function fovs(){let r=stage.getBoundingClientRect(),w=r.width,h=r.height,html="";for(const o of S.objects.filter(x=>x.type==="camera")){let c=camSpec(o),cx=o.x*w,cy=o.y*h,rr=o.range*Math.min(w,h);if(c.panoramic||c.hfov>=180){html+='<circle class="fov" cx="'+cx+'" cy="'+cy+'" r="'+rr+'"/><circle class="dori-red" cx="'+cx+'" cy="'+cy+'" r="'+rr*.78+'"/><circle class="dori-yellow" cx="'+cx+'" cy="'+cy+'" r="'+rr*.52+'"/><circle class="dori-green" cx="'+cx+'" cy="'+cy+'" r="'+rr*.28+'"/>'}else{html+='<polygon class="fov" points="'+wedge(cx,cy,rr,o.rot,c.hfov)+'"/><polygon class="dori-red" points="'+wedge(cx,cy,rr*.78,o.rot,c.hfov)+'"/><polygon class="dori-yellow" points="'+wedge(cx,cy,rr*.52,o.rot,c.hfov)+'"/><polygon class="dori-green" points="'+wedge(cx,cy,rr*.28,o.rot,c.hfov)+'"/>'}}overlay.innerHTML=html}
function render(){stage.querySelectorAll(".obj,.objLabel").forEach(e=>e.remove());for(const o of S.objects){let d=document.createElement("div");d.className="obj "+o.type+(o.id===S.selected?" selected":"");d.textContent=o.name;d.style.left=o.x*100+"%";d.style.top=o.y*100+"%";d.dataset.id=o.id;stage.append(d);let l=document.createElement("div");l.className="objLabel";l.textContent=o.name+(o.model?" · "+o.model:"");l.style.left=o.x*100+"%";l.style.top=o.y*100+"%";stage.append(l)}empty.style.display=(S.plan||S.objects.length)?"none":"grid";fovs();inspector();list();$("#undoBtn").disabled=!S.history.length}
function groupedOptions(arr,sel){return '<option value="">-- Välj modell --</option>'+["Axis","Hikvision","Dahua","Ajax"].map(b=>{let q=arr.filter(x=>x.brand===b);return q.length?'<optgroup label="'+b+'">'+q.map(x=>'<option value="'+esc(x.model)+'" '+(x.model===sel?"selected":"")+'>'+esc(x.model)+'</option>').join("")+"</optgroup>":""}).join("")}
function inspector(){let o=S.objects.find(x=>x.id===S.selected),el=$("#inspector");if(!o){el.innerHTML="Välj ett objekt på ritningen.";return}let arr=models(o.type);el.innerHTML='<b>'+o.name+'</b><div class="brand">'+esc(o.type.toUpperCase())+'</div><label>Modell<select id="modelSelect">'+groupedOptions(arr,o.model)+'</select></label>'+(o.type==="camera"?'<label>Rotation <b id="rotVal">'+o.rot+'°</b><input id="rotInput" type="range" min="0" max="359" value="'+o.rot+'"></label><label>Synfältslängd<input id="rangeInput" type="range" min="8" max="60" value="'+Math.round(o.range*100)+'"></label><div class="rotateBtns"><button data-r="-45">↶ 45°</button><button data-r="45">45° ↷</button></div>':"");$("#modelSelect").onchange=e=>{push();o.model=e.target.value;render()};if(o.type==="camera"){$("#rotInput").oninput=e=>{o.rot=+e.target.value;render()};$("#rangeInput").oninput=e=>{o.range=+e.target.value/100;fovs()};el.querySelectorAll("[data-r]").forEach(b=>b.onclick=()=>{push();o.rot=(o.rot+ +b.dataset.r+360)%360;render()})}}
function list(){$("#camList").innerHTML=S.objects.map(o=>'<div class="row" data-sel="'+o.id+'"><b>'+o.name+'</b><br><small>'+esc(o.model)+'</small></div>').join("")}
let drag=null;stage.addEventListener("pointerdown",e=>{let d=e.target.closest(".obj");if(!d)return;e.preventDefault();let o=S.objects.find(x=>x.id===d.dataset.id),r=stage.getBoundingClientRect();push();S.selected=o.id;drag={id:o.id,node:d,p:e.pointerId,dx:e.clientX-(r.left+o.x*r.width),dy:e.clientY-(r.top+o.y*r.height)};try{stage.setPointerCapture(e.pointerId)}catch{}inspector();list()});stage.addEventListener("pointermove",e=>{if(!drag)return;e.preventDefault();let r=stage.getBoundingClientRect(),o=S.objects.find(x=>x.id===drag.id);o.x=Math.max(.015,Math.min(.985,(e.clientX-r.left-drag.dx)/r.width));o.y=Math.max(.02,Math.min(.98,(e.clientY-r.top-drag.dy)/r.height));drag.node.style.left=o.x*100+"%";drag.node.style.top=o.y*100+"%";let labels=[...stage.querySelectorAll(".objLabel")],idx=S.objects.indexOf(o);if(labels[idx]){labels[idx].style.left=o.x*100+"%";labels[idx].style.top=o.y*100+"%"}fovs()});stage.addEventListener("pointerup",()=>{if(drag){drag=null;render()}});stage.onclick=e=>{let d=e.target.closest(".obj");if(d){S.selected=d.dataset.id;render()}};$("#camList").onclick=e=>{let r=e.target.closest("[data-sel]");if(r){S.selected=r.dataset.sel;render()}};
document.querySelectorAll("[data-add]").forEach(b=>b.onclick=()=>add(b.dataset.add));$("#planBtn").onclick=()=>$("#planFile").click();$("#planFile").onchange=e=>{let f=e.target.files[0];if(!f)return;let rd=new FileReader();rd.onload=()=>{S.plan=rd.result;plan.src=S.plan;try{localStorage.setItem("cctvPlan",S.plan)}catch{}status.textContent="Ritning laddad.";render()};rd.readAsDataURL(f)};
function data(){return {version:8,name:$("#projectName").value,objects:S.objects,scale:S.scale,plan:S.plan}}function load(q){S.objects=q.objects||[];S.scale=q.scale||null;S.plan=q.plan||null;S.selected=null;$("#projectName").value=q.name||"Projekt";if(S.plan)plan.src=S.plan;else plan.removeAttribute("src");render()}
$("#saveBtn").onclick=()=>{localStorage.setItem("cctvProject",JSON.stringify(data()));status.textContent="Projekt sparat lokalt."};$("#loadBtn").onclick=()=>{let x=localStorage.getItem("cctvProject");if(!x)return status.textContent="Inget sparat projekt hittades.";try{load(JSON.parse(x));status.textContent="Sparat projekt laddat."}catch{status.textContent="Kunde inte läsa projektet."}};
$("#exportBtn").onclick=()=>{let b=new Blob([JSON.stringify(data(),null,2)],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(b);a.download=($("#projectName").value||"cctv-project").replace(/[^a-z0-9_-]/gi,"_")+".json";a.click();URL.revokeObjectURL(a.href)};$("#importBtn").onclick=()=>$("#importFile").click();$("#importFile").onchange=e=>{let f=e.target.files[0];if(!f)return;let rd=new FileReader();rd.onload=()=>{try{load(JSON.parse(rd.result));status.textContent="Projekt importerat."}catch{status.textContent="Ogiltig projektfil."}};rd.readAsText(f)};
$("#undoBtn").onclick=()=>{if(!S.history.length)return;let q=JSON.parse(S.history.pop());S.objects=q.objects;S.selected=q.selected;S.scale=q.scale;render()};$("#newBtn").onclick=()=>{if(!confirm("Skapa nytt tomt projekt?"))return;S.objects=[];S.selected=null;S.plan=null;plan.removeAttribute("src");render()};$("#scaleBtn").onclick=()=>status.textContent="Tvåpunktskalibrering är nästa steg.";
function norm(v){return v.toLowerCase().replace(/axis\s+/g,"").replace(/[^a-z0-9]/g,"")}
function findCameraModel(text){let n=norm(text),best=null;for(const c of CAT.cameras){let cm=norm(c.model);if(n.includes(cm)||cm.includes(n)){if(!best||cm.length>norm(best.model).length)best=c}}return best}
function expandK(expr){let out=[];expr=expr.toUpperCase().replace(/\s+/g,"");for(const part of expr.split(",")){let m=part.match(/^K(\d+)-K?(\d+)$/);if(m){for(let n=+m[1];n<=+m[2];n++)out.push("K"+n)}else if(/^K\d+$/.test(part))out.push(part)}return out}
function runAI(){let t=$("#aiPrompt").value.trim();if(!t)return;push();let changed=0,errors=[];let clauses=t.split(/[.;\n]+/).map(x=>x.trim()).filter(Boolean);for(let clause of clauses){let km=clause.match(/((?:K\d+\s*(?:,|och|-)?\s*)+)/i);if(!km)continue;let ids=expandK(km[1].replace(/\boch\b/gi,","));let model=findCameraModel(clause);if(!model){errors.push(ids.join(",")+": kameramodell hittades inte");continue}for(let id of ids){let o=S.objects.find(x=>x.type==="camera"&&x.name.toUpperCase()===id);if(!o){errors.push(id+" finns inte");continue}o.model=model.model;changed++}let rr=clause.match(/(\d{1,3})\s*(?:°|grader)/i);if(rr)for(let id of ids){let o=S.objects.find(x=>x.type==="camera"&&x.name.toUpperCase()===id);if(o){o.rot=(+rr[1])%360;changed++}}}status.textContent=errors.length?((changed?changed+" ändring(ar). ":"")+errors.join(" · ")):changed?changed+" ändring(ar) utförda. K-positionerna är oförändrade.":"Ingen säker K/modell-instruktion hittades.";render()}$("#aiBtn").onclick=runAI;
let saved=localStorage.getItem("cctvProject");if(saved)try{load(JSON.parse(saved))}catch{}else{let p=localStorage.getItem("cctvPlan");if(p){S.plan=p;plan.src=p}render()}
})();